load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "opencv_demo",
    srcs = ["main.cc"],
    deps = [
        "@opencv//:opencv",
    ],
)